CHECK_INS = [
    "goodmorning",
    "howwedoin",
    "howyoudoin",
    "howwelivin",
    "howyoulivin",
    "howsitgoin",
    "howareyou",
    "areyouok",
    "whatsgood",
    "whatsgoinon",
    "whatsgoingon",
    "whatsup",
    "whatup",
    "whaddup",
    "whatspoppin",
    "whatshappenin",
    "whatscrackin",
    "whereyoubeen",
    "whereareyou",
]

LAUGHS = {
    "lol",
    "loll",
    "lolll",
    "lolll",
    "lmao",
    "lmaoo",
    "lmaooo",
    "haha",
    "lmfao",
    "😂",
    "🤣",
    "😅",
    "😆",
}

NEGATIVES = {
    "jesus dude",
    "bruh",
    "wtf",
    "not cool",
    "not chill",
    "no chill",
    "damn bro",
    "damn dude",
    "damn bbot",
    "fuck you",
    "fuck off",
    "bad bot",
}

POSITIVES = {
    "yess",
    "yaww",
    "chya",
    "eyaw",
    "hell y",
    "yes bbot",
    "fuck ye",
    "love it",
    "my man",
    "my guy",
    "bro",
    "thank you",
    "thanks",
    "absolutely",
    "welcome",
    "the best",
    "friend",
    "gets it",
}

REASON_PREFIXES = [
    'because',
    'cause',
    'basically cause',
    'just because',
    'basically just because',
    'only because',
    'pretty much just because',
    'only cause',
    'well,',
    'basically,',
    'here\'s the deal',
    'dude,',
    'bruh,',
    'bro,',
    'dude',
]