GREETINGS = {"good morning", "morning", "hello", "hi "}

CHECK_INS = [
    "how we doin",
    "how you doin",
    "how we livin" "how you livin",
    "how's it goin",
    "hows it goin",
    "how are you",
    "are you ok",
    "what's good",
    "whats good",
    "whatsup",
    "whats up",
    "whatup",
    "whaddup",
    "whats poppin",
    "whats happenin",
    "what's happenin",
    "what's crackin",
    "whats crackin",
    "how are you",
    "where you been",
    "where are you",
]

GREETING_RESPONSES = [
    "whatup",
    "hey",
    "ay",
    "ayyyy",
    "chyaa",
    "chyaaa",
    "eyaww",
    "eyawww",
    "eyawwww",
    "ayoo",
    "ayyy",
    "whatupp",
    "yo yo",
    "yooo",
]

GREETING_QUESTIONS = [
    "how we doing",
    "how you doing",
    "what's good",
    "how's it going",
    "how we doing",
    "how you doing",
    "what's good",
    "how's it going",
    "how we doing",
    "how you doing",
    "what's good",
    "how's it going",
    "hows your belly feeling",
    "hows ur bb feeling",
    "sweaty bb?",
    "hows your week goin",
    "whats new playa",
    "eat any good ass lately?",
]

LAUGHS = {
    "lol",
    "loll",
    "lolll",
    "lolll",
    "lmao",
    "lmaoo",
    "lmaooo",
    "haha",
    "lmfao",
    "😂",
    "🤣",
    "😅",
    "😆",
}

NEGATIVES = {
    "jesus dude",
    "bruh",
    "wtf",
    "not cool",
    "not chill",
    "no chill",
    "damn bro",
    "damn dude",
    "damn bbot",
    "fuck you",
    "fuck off",
    "bad bot",
}

POSITIVES = {
    "yess",
    "yesss",
    "yaww",
    "yawww",
    "chya",
    "chyaa",
    "chyaaa",
    "eyaw",
    "eyaww",
    "hell ye",
    "hell ya",
    "yes bbot",
    "fuck ye",
    "love it",
    "my man",
    "my guy",
    "bro",
    "thank you",
    "thanks",
    "absolutely",
}

QUESTIONS = {
    "wanna",
    "want",
    "are",
    "did",
    "do",
    "have",
    "will",
    "can",
    "what",
    "whats",
    "what's",
    "how",
    "hows",
    "how's",
    "when",
    "whens",
    "when's",
    "who",
    "whos",
    "whose",
    "who's",
    "why",
    "whys",
    "why's",
}
