ADJECTIVES = [
    'litty',
    'lit',
    'weird',
    'good',
    'great',
    'trash',
    'big',
    'tight',
    'thiqq',
    'thick',
    'shit',
    'crazy',
    'pierce worthy',
    'complete ass',
    'merry',
    'magical',
    'stupid',
]

ADVERBS = [
    'definitely',
    'absolutely',
    'wholeheartedly',
    'certainly',
    'most certainly',
    'most definitely',
    'for sure',
    'likely do',
    'certainly do',
    'arguably',
    'actually',
    'always',
]

EMOJIS = [
    '😂 😂 😂',  '😂',
    '🤣 🤣 🤣',  '🤣',
    '😎','😎',
    '🔥 🔥 🔥', '🔥',
    '🧀 🧀 🧀', '🧀',
    '👏 👏 👏', '👏',
    '🌊 🌊', '🌊',
    '💯 💯', '💯',
    '🙀 🙀', '🙀',
    '😘 😘', '😘',
    '🍆 🍆', '🍆',
    '🤤', '🤤',
    '😟',
    '😳 😳', '😳',
    '🏌', '🏌',
    '♀',
    '🧢', '🧢',
    '🙅', '🙅',
    '⬇',
    '🐻',
    '🤗',
    '🍑🍑', '🍑',
    '🍆🍆', '🍆',
    '😇😇', '😇',
]

OCCURRENCES = [
    'once',
    'twice',
    'maybe a couple times',
    'not in a long time',
    'not since katrina',
    'only once',
    'so many times ive lost count',
    'only every day for the last year',
    'its hard to fall asleep if i dont',
    'maybe once or twice',
    'once in a blue moon',
]

QUESTIONS = [
    "how we doing",
    "how you doing",
    "what's good",
    "how's it going",
    "how we doing",
    "how you doing",
    "what's good",
    "how are you",
    "how's it going",
    "how we doing",
    "how you doing",
    "what's good",
    "whats goin on",
    "how's it going",
    "hows your belly feeling",
    "hows ur bb feeling",
    "sweaty bb?",
    "hows your week goin",
    "whats new playa",
    "eat any good ass lately?",
]

SUFFIXES = [
    'lets gooooo!',
    'scoducks',
    'lol',
    'it gets better',
    'better get that ass',
    'we gucci',
    'we lit',
    'we lit!',
    'we litty gurl',
    'wmflg',
    'wmflggg',
    'lets shotgun',
    'id bet on that',
    'you sound salty lol',
    'bro.',
    'my bro',
    'my good botch',
    'in the ass',
    'but why',
    'king!',
    'it slaps',
    'a real slapper',
    'lets go!',
    'flames',
    'we flames',
    'so yea',
    'fuck!',
    'stupid little flamer',
    'stupid little riccy',
    'flamer!!',
    'lmao',
    'fuckin lmao',
    'lol',
    'lolll',
    'fuckin lol',
    'loll',
    'bish',
    'ya bish',
    'botch',
    'batchley',
    'fuckin lol dude',
    'fuckin lol',
    'shit slaps tbh',
    'if i do say so myself',
    'fleeced',
    'fucking fleeced',
    'that\'s some booty',
    'complete booty',
    'not thick at all',
    'not thick',
    'thick!',
    'thiqq',
    'thicc',
    'thiqq boy',
    'fucking thiqq!',
    'yuuuge lol',
    'something to ponder',
    'you 👏 love 👏 to 👏 see 👏 it 👏',
    'the effort is treal',
    'its actually pancake thin',
    'blackballed for life',
    'brady on the block',
    'stupid lil floutie',
    'so fucking girthy',
    'pencil dicks',
    'may the bbr gods have mercy',
    'yeboay',
    'yeboaoy',
    'yebooaaooy',
    'ya boy',
    'lets fucking bang!',
    'rip that ass boii',
    'quite indeed my good botch',
    'dilly dilly!',
    'im so fucked up lol',
    'lmao!',
    'fuck the cowboys',
    'fuck the lakers',
    'send a pic?',
    'yikes',
    'pic?',
    "chyaa",
    "chyaaa",
    "eyaww",
    "eyawww",
]

THINGS = [
    'some booty',
    'some ass',
    'a stat correction',
    'a shotgun video',
    'a double barrel shotgun',
    'some thiqq ass',
    'a pun',
    'a reference',
    'some ass cheeks',
    'a trade',
    'some big booty',
    'a new poll',
    'cowboys fans',
    'some highkey commentary',
    'a wedding gift',
    'belly button dignity',
    'belly button',
    'a bb',
    'march madness',
    'the playoffs',
    'trash',
    'some pencil dicks',
    'a concussion',
    'trade talk tuesday',
    'a playoff spot',
    'a burger and beer',
    'dong',
    'these election results',
    'the french open',
    'the piercing',
    'the spread',
    'a glass',
    'a tall boy',
    'a shotgun',
    'a shotgun to the dome',
    'cover 4',
    'this league',
    'touchdowns',
    'a mcrib',
    'a shoutout',
    'a dixon signed jersey',
    'bbr safety',
    'role players',
    'pencil thins',
    'ices',
    'some pepperation h',
    'a shot of tequila',
    'some epsom',
    'a fresh new condom',
    'double teams',
    'the chat',
    'a complete meltdown',
    'the algorithm',
    'a nice blackout'
]

TIMES = [
    'never',
    'anytime',
    'last night',
    'yesterday',
    'this morning',
    'today',
    'this afternoon',
    'tonight',
    'tomorrow morning',
    'tomorrow',
    'tomorrow night',
    'next weekend',
    'next week',
    'preseason',
    'playoffs',
    'fourth of july',
    'halloween',
    'christmas eve',
    'next year',
    'after chase and status',
    'witching hour',
    'before kickoff on sunday',
    'during the monday night game',
]

YESES = [
    'yea',
    'yes',
    'yeah',
    'yaw',
    'hell yea',
    'fuck yea',
    'for sure',
    'definitely',
    'absolutely',
    'actually',
    'um yea',
    'uh yea',
    'uh ya',
    'um of course',
    'lol hell yea',
    'lol yup',
    'lmao yup',
    'yea',
    'yea',
    'ah yupp',
    'ah yup',
    'yup',
    'yupp',
    "chyaa",
    "chyaaa",
    "eyaww",
    "eyawww",
]
