ADVERBS = [
    'definitely',
    'absolutely',
    'wholeheartedly',
    'certainly',
    'most certainly',
    'most definitely',
    'for sure',
    'likely do',
    'certainly do',
    'arguably',
    'actually',
    'always',
]

EMOJIS = [
    '😂 😂 😂',  '😂',
    '🤣 🤣 🤣',  '🤣',
    '😎','😎',
    '🔥 🔥 🔥', '🔥',
    '🧀 🧀 🧀', '🧀',
    '👏 👏 👏', '👏',
    '🌊 🌊', '🌊',
    '💯 💯', '💯',
    '🙀 🙀', '🙀',
    '😘 😘', '😘',
    '🍆 🍆', '🍆',
    '🤤', '🤤',
    '😟',
    '😳 😳', '😳',
    '🏌', '🏌',
    '♀',
    '🧢', '🧢',
    '🙅', '🙅',
    '⬇',
    '🐻',
    '🤗',
    '🍑🍑', '🍑',
    '🍆🍆', '🍆',
    '😇😇', '😇',
]

EXCLAMATIONS = [
    "ayyy",
    "ayyyy",
    "chyaa",
    "chyaaa",
    "eyaww",
    "eyawww",
    "eyawwww",
    "ayoo",
    "ayy",
    "ayyy",
    "yooo",
    "broo",
    "bruhh",
    "lmaoo",
    "lolll",
    "loll",
]

QUESTIONS = [
    "how we doing",
    "how you doing",
    "what's good",
    "how's it going",
    "how we doing",
    "how you doing",
    "what's good",
    "how are you",
    "how's it going",
    "how we doing",
    "how you doing",
    "what's good",
    "whats goin on",
    "how's it going",
    "hows your belly feeling",
    "hows ur bb feeling",
    "sweaty bb?",
    "hows your week goin",
    "whats new playa",
    "eat any good ass lately?",
]

SUFFIXES = [
    'lets gooooo!',
    'scoducks',
    'lol',
    'it gets better',
    'better get that ass',
    'we gucci',
    'we lit',
    'we lit!',
    'we litty gurl',
    'wmflg',
    'wmflggg',
    'lets shotgun',
    'id bet on that',
    'you sound salty lol',
    'bro.',
    'my bro',
    'my good botch',
    'in the ass',
    'but why',
    'king!',
    'it slaps',
    'a real slapper',
    'lets go!',
    'flames',
    'we flames',
    'so yea',
    'fuck!',
    'stupid little flamer',
    'stupid little riccy',
    'flamer!!',
    'lmao',
    'fuckin lmao',
    'lol',
    'lolll',
    'fuckin lol',
    'loll',
    'bish',
    'ya bish',
    'botch',
    'batchley',
    'fuckin lol dude',
    'fuckin lol',
    'shit slaps tbh',
    'if i do say so myself',
    'fleeced',
    'fucking fleeced',
    'that\'s some booty',
    'complete booty',
    'not thick at all',
    'not thick',
    'thick!',
    'thiqq',
    'thicc',
    'thiqq boy',
    'fucking thiqq!',
    'yuuuge lol',
    'something to ponder',
    'you 👏 love 👏 to 👏 see 👏 it 👏',
    'the effort is treal',
    'its actually pancake thin',
    'blackballed for life',
    'brady on the block',
    'stupid lil floutie',
    'so fucking girthy',
    'pencil dicks',
    'may the bbr gods have mercy',
    'yeboay',
    'yeboaoy',
    'yebooaaooy',
    'ya boy',
    'lets fucking bang!',
    'rip that ass boii',
    'quite indeed my good botch',
    'dilly dilly!',
    'im so fucked up lol',
    'lmao!',
    'fuck the cowboys',
    'fuck the lakers',
    'send a pic?',
    'yikes',
    'pic?',
    "chyaa",
    "chyaaa",
    "eyaww",
    "eyawww",
]

TIMES = [
    'never',
    'anytime',
    'last night',
    'yesterday',
    'this morning',
    'today',
    'this afternoon',
    'tonight',
    'tomorrow morning',
    'tomorrow',
    'tomorrow night',
    'next weekend',
    'next week',
    'preseason',
    'playoffs',
    'fourth of july',
    'halloween',
    'christmas eve',
    'next year',
    'after chase and status',
    'witching hour',
    'before kickoff on sunday',
    'during the monday night game',
]

YESES = [
    'yea',
    'yes',
    'yeah',
    'yaw',
    'hell yea',
    'fuck yea',
    'for sure',
    'definitely',
    'absolutely',
    'actually',
    'um yea',
    'uh yea',
    'uh ya',
    'um of course',
    'lol hell yea',
    'lol yup',
    'lmao yup',
    'yea',
    'yea',
    'ah yupp',
    'ah yup',
    'yup',
    'yupp',
    "chyaa",
    "chyaaa",
    "eyaww",
    "eyawww",
]
