PREFIXES = [
    "ayyy",
    "ayyyy",
    "chyaa",
    "chyaaa",
    "eyaww",
    "eyawww",
    "eyawwww",
    "ayoo",
    "ayy",
    "ayyy",
    "yooo",
    "loll",
    "lolll",
    "lmao",
    "broo",
    "bruhh",
]

QUESTIONS = [
    "how we doing",
    "how you doing",
    "what's good",
    "how's it going",
    "how we doing",
    "how you doing",
    "what's good",
    "how are you",
    "how's it going",
    "how we doing",
    "how you doing",
    "what's good",
    "whats goin on"
    "how's it going",
    "hows your belly feeling",
    "hows ur bb feeling",
    "sweaty bb?",
    "hows your week goin",
    "whats new playa",
    "eat any good ass lately?",
]

SUFFIXES = [
    'lets gooooo!',
    'scoducks',
    'lol',
    'it gets better',
    'better get that ass',
    'we gucci',
    'we lit',
    'we lit!',
    'we litty gurl',
    'wmflg',
    'wmflggg',
    'lets shotgun',
    'id bet on that',
    'you sound salty lol',
    'broo',
    'bro.',
    'my bro',
    'my good botch',
    'in the ass',
    'but why',
    'king!',
    'it slaps',
    'a real slapper',
    'lets go!',
    'flames',
    'we flames',
    'so yea',
    'fuck!',
    'stupid little flamer',
    'stupid little riccy',
    'flamer!!',
    'lmao',
    'lmao',
    'fuckin lmao',
    'lol',
    'lolll',
    'fuckin lol',
    'loll',
    'bish',
    'ya bish',
    'botch',
    'batchley',
    'fuckin lol dude',
    'fuckin lol',
    'shit slaps tbh',
    'if i do say so myself',
    'fleeced',
    'fucking fleeced',
    'that\'s some booty',
    'complete booty',
    'not thick at all',
    'not thick',
    'thick!',
    'thiqq',
    'thicc',
    'thiqq boy',
    'fucking thiqq!',
    'yuuuge lol',
    'something to ponder',
    'you 👏 love 👏 to 👏 see 👏 it 👏',
    'the effort is treal',
    'its actually pancake thin',
    'blackballed for life',
    'brady on the block',
    'stupid lil floutie',
    'so fucking girthy',
    'pencil dicks',
    'may the bbr gods have mercy',
    'yeboay',
    'yeboaoy',
    'yebooaaooy',
    'ya boy',
    'lets fucking bang!',
    'rip that ass boii',
    'quite indeed my good botch',
    'dilly dilly!',
    'im so fucked up lol',
    'lmao!'
    'fuck the cowboys',
    'send a pic?',
    'yikes'
]

YESES = [
    'yea',
    'yes',
    'yeah',
    'yaw',
    'chyaa',
    'chyaaa',
    'eyaww',
    'eyawww',
    'hell yea',
    'fuck yea',
    'for sure',
    'definitely',
    'absolutely',
    'actually',
    'um yea',
    'uh yea',
    'uh ya',
    'um of course',
    'lol hell yea',
    'lol yup',
    'lmao yup',
    'yea',
    'yea',
    'ah yupp',
    'ah yup',
    'yup',
    'yupp'
]

EMOJIS = [
    '😂 😂 😂',  '😂',
    '🤣 🤣 🤣',  '🤣',
    '😎','😎',
    '🔥 🔥 🔥', '🔥',
    '🧀 🧀 🧀', '🧀',
    '👏 👏 👏', '👏',
    '🌊 🌊', '🌊',
    '💯 💯', '💯',
    '🙀 🙀', '🙀',
    '😘 😘', '😘',
    '🍆 🍆', '🍆',
    '🤤', '🤤',
    '😟',
    '😳 😳', '😳',
    '🏌', '🏌',
    '♀', ' ♀',
    '🧢', '🧢',
    '🙅', '🙅',
    '⬇',
    '🐻'
]