version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis:
    image: redis
  django:
    build:
      context: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/django
    ports:
      - "8000:8000"
    depends_on:
      - db
    tty: true
  flask:
    build: ./flask
    volumes:
      - ./flask/:/code
    ports:
      - 5000:5000
    depends_on:
      - redis
    restart: "always"
  react:
    build:
      context: ./react
      dockerfile: Dockerfile-dev
    volumes:
      - ./react/:/code
    ports:
      - 3000:3000
    depends_on:
      - flask
    tty: true

volumes:
  pgdata: