# Generated by Django 3.1.7 on 2021-03-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.content')),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('caption', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.content')),
                ('content', models.TextField()),
            ],
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.content')),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('caption', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.content')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='content.Image'),
        ),
        migrations.AddField(
            model_name='page',
            name='texts',
            field=models.ManyToManyField(blank=True, null=True, to='content.Text'),
        ),
        migrations.AddField(
            model_name='page',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='content.Video'),
        ),
    ]
