# Generated by Django 3.1.7 on 2021-03-28 18:06

from django.db import migrations


MEMBERS = [
    {
        "name": "bbot",
        "groupme_id": "845869",
        "avatar_url": None 
    },
    {
        "name": "bk",
        "groupme_id": "30837255",
        "avatar_url": None 
    },
    {
        "name": "bry",
        "groupme_id": "30837257",
        "avatar_url": None 
    },
    {
        "name": "calero",
        "groupme_id": "30837252",
        "avatar_url": None 
    },
    {
        "name": "cam",
        "groupme_id": "30837254",
        "avatar_url": None 
    },
    {
        "name": "frank",
        "groupme_id": "30837256",
        "avatar_url": None 
    },
    {
        "name": "greg",
        "groupme_id": "4689709",
        "avatar_url": None 
    },
    {
        "name": "j-shaw",
        "groupme_id": "87582812",
        "avatar_url": None 
    },
    {
        "name": "jerad",
        "groupme_id": "30837253",
        "avatar_url": None 
    },
    {
        "name": "max",
        "groupme_id": "30803718",
        "avatar_url": None 
    },
    {
        "name": "pat",
        "groupme_id": "30837258",
        "avatar_url": None 
    },
    {
        "name": "rene",
        "groupme_id": "30833338",
        "avatar_url": None 
    },
    {
        "name": "shane",
        "groupme_id": "22026356",
        "avatar_url": None 
    },
    {
        "name": "trav",
        "groupme_id": "4037223",
        "avatar_url": None 
    },
    {
        "name": "vino",
        "groupme_id": "30803449",
        "avatar_url": 'https://i.groupme.com/500x500.jpeg.435aad4799ea4a5aab12a07360495776' 
    },
    {
        "name": "walsh",
        "groupme_id": "30837259",
        "avatar_url": None 
    }
]


PAGES = {
  'Top All Time': "top",
  'BBTV': "watch",
  'The Shotty Shoutouts': "shoutouts",
}


def create_objects(apps, schema_editor):
    member_model = apps.get_model("content", "Member")
    page_model = apps.get_model("content", "Page")

    for member in MEMBERS:
        member_model.objects.get_or_create(
            name=member['name'],
            groupme_id=member['groupme_id'],
            avatar_url=member['avatar_url']
        )
    for name, slug in PAGES.items():
        page_model.objects.get_or_create(
            name=name,
            slug=slug
        )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_objects, reverse_code=migrations.RunPython.noop),
    ]
