# Generated by Django 3.1.7 on 2021-03-18 17:04
from django.contrib.auth.models import User
from django.db import migrations


USERS = {
  '4689709': "greg",
  '30833338': "rene",
  '22026356': "shane",
  '30837253': "jerad",
  '30803449': "vino",
  '30837254': "cam",
  '30837259': "walsh",
  '4037223': "trav",
  '87582812': 'j-shaw',
  '30837255': 'bk',
  '30837252': 'calero',
  '845869': 'bbot',
}


def create_users(apps, schema_editor):
    for groupme_id, username in USERS.items():
        user, _ = User.objects.get_or_create(
            username=username
        )
        user.profile.groupme_id = groupme_id
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users, reverse_code=migrations.RunPython.noop),
    ]