# Generated by Django 3.1.7 on 2021-04-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210401_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['?'], 'verbose_name_plural': 'Content'},
        ),
        migrations.AddField(
            model_name='content',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='contents',
            field=models.ManyToManyField(blank=True, null=True, related_name='pages', to='content.Content'),
        ),
    ]
