# Generated by Django 3.1.7 on 2021-03-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210318_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='kind',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], default='TEXT', max_length=10),
        ),
    ]
