# Generated by Django 3.1.7 on 2021-03-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_delete_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
