# Generated by Django 3.1.7 on 2021-03-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='creator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
