# Generated by Django 3.1.7 on 2021-03-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['?']},
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
