# Generated by Django 3.2 on 2021-04-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_order', models.PositiveIntegerField(default=0)),
                ('contents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.content')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.page')),
            ],
            options={
                'ordering': ('content_order',),
            },
        ),
    ]
