# Generated by Django 3.1.7 on 2021-03-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210319_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='content',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
