# Generated by Django 3.1.7 on 2021-03-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.content')),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['-create_date'],
            },
            bases=('content.content',),
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-create_date']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='caption',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='image',
            name='date',
        ),
        migrations.RemoveField(
            model_name='page',
            name='texts',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date',
        ),
        migrations.AddField(
            model_name='content',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.AddField(
            model_name='page',
            name='quotes',
            field=models.ManyToManyField(blank=True, null=True, to='content.Quote'),
        ),
    ]
