# Generated by Django 3.1.7 on 2021-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210318_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
