# Generated by Django 3.1.7 on 2021-03-28 18:06

from django.db import migrations


PAGES = {
  'Top All Time': "top",
  'Best of Bot': "bot",
  'BBTV': "watch",
  'The Shotty Shoutouts': "shoutouts",
  'Early Content': "early",
}


def create_pages(apps, schema_editor):
    page_model = apps.get_model("content", "Page")
    for name, slug in PAGES.items():
        page_model.objects.get_or_create(
            name=name,
            slug=slug
        )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210322_2106'),
    ]

    operations = [
        migrations.RunPython(create_pages, reverse_code=migrations.RunPython.noop),
    ]
