# Generated by Django 3.1.8 on 2021-04-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_pagecontents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='contents',
        ),
        migrations.AddField(
            model_name='page',
            name='contents',
            field=models.ManyToManyField(blank=True, null=True, related_name='pages', through='content.PageContents', to='content.Content'),
        ),
    ]
