# Generated by Django 3.1.8 on 2021-04-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210413_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecontents',
            old_name='contents',
            new_name='content',
        ),
    ]
