# Generated by Django 3.1.8 on 2021-04-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210413_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('caption', models.TextField(blank=True, null=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pagecontents',
            options={'ordering': ('content_order',), 'verbose_name_plural': 'Page Contents'},
        ),
        migrations.CreateModel(
            name='ImageSliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.image')),
                ('slider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.imageslider')),
            ],
            options={
                'verbose_name_plural': 'Slider image',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='imageslider',
            name='images',
            field=models.ManyToManyField(related_name='sliders', through='content.ImageSliderImages', to='content.Image'),
        ),
        migrations.AddField(
            model_name='imageslider',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sliders', to='content.page'),
        ),
    ]
