# Generated by Django 3.1.8 on 2021-04-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20210417_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageslider',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
