# Generated by Django 3.1.13 on 2021-07-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_create_nfl_teams'),
        ('content', '0008_auto_20210418_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nfl_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.nflteam'),
        ),
    ]
