# Generated by Django 3.1.11 on 2021-05-28 19:10

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pos', models.CharField(choices=[('NOUN', 'NOUN'), ('PRONOUN', 'PRONOUN'), ('VERB', 'VERB'), ('ADJECTIVE', 'ADJECTIVE'), ('ADVERB', 'ADVERB'), ('PREPOSITION', 'PREPOSITION'), ('CONJUNCTION', 'CONJUNCTION'), ('INTERJECTION', 'INTERJECTION')], max_length=20)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
