# Generated by Django 3.1.11 on 2021-05-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.CharField(blank=True, choices=[('NOUN', 'NOUN'), ('PRONOUN', 'PRONOUN'), ('VERB', 'VERB'), ('ADJECTIVE', 'ADJECTIVE'), ('ADVERB', 'ADVERB'), ('PREPOSITION', 'PREPOSITION'), ('CONJUNCTION', 'CONJUNCTION'), ('INTERJECTION', 'INTERJECTION')], max_length=20, null=True),
        ),
    ]
