# Generated by Django 3.1.11 on 2021-05-31 01:04

from django.db import migrations

from bot.data.groupme_messages import MESSAGES


def create_objects(apps, schema_editor):
    word_model = apps.get_model("language", "Word")

    count = 0
    for message in MESSAGES:
        for w in message.split():
            if len(w) < 100:
                word, created = word_model.objects.get_or_create(name=w)
                if created:
                    count += 1
                    print(f'{count}: {word}')


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_auto_20210528_2010'),
    ]

    operations = [
        migrations.RunPython(create_objects, reverse_code=migrations.RunPython.noop),
    ]
