# Generated by Django 3.1.11 on 2021-05-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_auto_20210531_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='tense',
            field=models.CharField(blank=True, choices=[('PAST', 'PAST'), ('PRESENT', 'PRESENT'), ('FUTURE', 'FUTURE')], max_length=100, null=True),
        ),
    ]
