apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbrnation-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbrnation-backend
  template:
    metadata:
      labels:
        app: bbrnation-backend
    spec:
      containers:
        - name: django
          image: "gcr.io/optimum-pier-280005/bbrnation-backend:latest"
          ports:
            - name: http
              containerPort: 8000
        - name: db
          image: postgres
          env:
            - name: "POSTGRES_DB"
              value: "postgres"
            - name: "POSTGRES_USER"
              value: "postgres"
            - name: "POSTGRES_PASSWORD"
              value: "postgres"
          ports:
            - containerPort: 5432
