# Generated by Django 3.1.11 on 2021-06-16 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0008_auto_20210418_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bachelorette.draft')),
                ('draftee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bachelorette.contestant')),
                ('drafter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.member')),
            ],
        ),
    ]
