# Generated by Django 3.1.11 on 2021-06-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachelorette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestant',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
