# Generated by Django 3.1.11 on 2021-06-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachelorette', '0002_auto_20210616_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='drafted',
            field=models.BooleanField(default=False),
        ),
    ]
