# Generated by Django 3.1.11 on 2021-06-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachelorette', '0004_auto_20210616_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='player',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
