# Generated by Django 3.1.11 on 2021-06-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachelorette', '0005_draftpick_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='draftpick',
            name='pick',
            field=models.IntegerField(default=0),
        ),
    ]
