# Generated by Django 3.1.11 on 2021-06-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('YES', 'YES'), ('TIME', 'TIME'), ('QUESTION', 'QUESTION'), ('ADVERB', 'ADVERB'), ('EXCLAMATION', 'EXCLAMATION'), ('QUESTION', 'QUESTION'), ('SUFFIX', 'SUFFIX'), ('EMOJI', 'EMOJI')], max_length=20)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
