# Generated by Django 3.1.11 on 2021-06-03 01:15
from django.db import migrations

from bot.vocab import nouns, phrases


def create_objects(apps, schema_editor):
    phrase_model = apps.get_model("vocab", "Phrase")
    person_model = apps.get_model("vocab", "Person")
    place_model = apps.get_model("vocab", "Place")

    for name in nouns.PEOPLE:
        person_model.objects.get_or_create(name=name)

    for name in nouns.PLACES:
        place_model.objects.get_or_create(name=name)

    for yes in phrases.YESES:
        phrase_model.objects.get_or_create(
            text=yes,
            kind='YES'
        )
    
    for suffix in phrases.SUFFIXES:
        phrase_model.objects.get_or_create(
            text=suffix,
            kind='SUFFIX'
        )

    for exclamation in phrases.EXCLAMATIONS:
        phrase_model.objects.get_or_create(
            text=exclamation,
            kind='EXCLAMATION'
        )

    for question in phrases.QUESTIONS:
        phrase_model.objects.get_or_create(
            text=question,
            kind='QUESTION'
        )

    for emoji in phrases.EMOJIS:
        phrase_model.objects.get_or_create(
            text=emoji,
            kind='EMOJI'
        )

    for adverb in phrases.ADVERBS:
        phrase_model.objects.get_or_create(
            text=adverb,
            kind='ADVERB'
        )

    for time in phrases.TIMES:
        phrase_model.objects.get_or_create(
            text=time,
            kind='TIME'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_objects, reverse_code=migrations.RunPython.noop),
    ]
