# Generated by Django 3.1.11 on 2021-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_auto_20210603_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
