# Generated by Django 3.1.11 on 2021-06-18 16:27

from django.db import migrations

from bot.vocab import nouns

def create_objects(apps, schema_editor):
    team_name_model = apps.get_model("vocab", "TeamName")

    for name in nouns.TEAM_NAMES:
        team_name_model.objects.get_or_create(
            name=name
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_teamname'),
    ]

    operations = [
        migrations.RunPython(create_objects, reverse_code=migrations.RunPython.noop),
    ]
