# Generated by Django 3.1.11 on 2021-06-26 03:38

from django.db import migrations


def create_objects(apps, schema_editor):
    bot_model = apps.get_model("bot", "GroupMeBot")
    phrase_model = apps.get_model("vocab", "Phrase")

    bbot_id = bot_model.objects.filter(name='bbot').first()

    if bbot_id:
        for phrase in phrase_model.objects.all():
            phrase.bot_id = bbot_id
            phrase.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_phrase_bot'),
    ]

    operations = [
        migrations.RunPython(create_objects, reverse_code=migrations.RunPython.noop),
    ]
