# Generated by Django 3.1.7 on 2021-04-04 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerseason',
            name='draft_pick',
        ),
        migrations.RemoveField(
            model_name='playerseason',
            name='games_played',
        ),
        migrations.AddField(
            model_name='player',
            name='espn_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playerseason',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.team'),
        ),
    ]
