# Generated by Django 3.1.7 on 2021-04-04 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_auto_20210404_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='standing',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='football.season'),
        ),
    ]
