# Generated by Django 3.1.7 on 2021-04-05 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_auto_20210404_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseason',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons', to='football.player'),
        ),
    ]
