# Generated by Django 3.1.13 on 2021-07-18 16:33

from django.db import migrations

from football import NFL


def create_objects(apps, schema_editor):
    nfl_conference = apps.get_model("football", "NFLConference")
    nfl_division = apps.get_model("football", "NFLDivision")
    nfl_team = apps.get_model("football", "NFLTeam")

    for c in NFL.keys():
        conference, _ = nfl_conference.objects.get_or_create(
            name=c
        )
        for d in NFL[c].keys():
            division, _ = nfl_division.objects.get_or_create(
                name=d,
                conference_id=conference.id
            )
            for team in NFL[c][d]:
                nfl_team.objects.get_or_create(
                    name=team,
                    division_id=division.id,
                    nicknames=[]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_nflconference_nfldivision_nflseason_nflteam'),
    ]

    operations = [
        migrations.RunPython(create_objects, reverse_code=migrations.RunPython.noop),
    ]
