# Generated by Django 3.1.8 on 2021-05-06 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0008_auto_20210418_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMeBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('NEUTRAL', 'NEUTRAL'), ('POSITIVE', 'POSITIVE'), ('NEGATIVE', 'NEGATIVE'), ('LAUGHING', 'LAUGHING')], max_length=10, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('question', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.member')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('request', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.request')),
            ],
        ),
    ]
