# Generated by Django 3.1.8 on 2021-05-06 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210506_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmebot',
            name='user_id',
        ),
    ]
