# Generated by Django 3.1.8 on 2021-05-06 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_groupmebot_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.groupmebot'),
        ),
    ]
