# Generated by Django 3.1.10 on 2021-05-10 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_auto_20210413_1950'),
        ('content', '0008_auto_20210418_1558'),
        ('bot', '0004_response_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='question',
            new_name='is_greeting',
        ),
        migrations.AddField(
            model_name='request',
            name='direct_object',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='greeting_word',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='is_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='question_word',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='verb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('used', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('sentiment', models.CharField(choices=[('NEUTRAL', 'NEUTRAL'), ('POSITIVE', 'POSITIVE'), ('NEGATIVE', 'NEGATIVE'), ('LAUGHING', 'LAUGHING')], default='NEUTRAL', max_length=15)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thoughts', to='content.member')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thoughts', to='football.player')),
            ],
        ),
    ]
