# Generated by Django 3.1.10 on 2021-05-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_request_is_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
