# Generated by Django 3.1.10 on 2021-05-19 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_thought_is_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='greeting_word',
        ),
        migrations.AddField(
            model_name='request',
            name='message_type',
            field=models.CharField(blank=True, choices=[('GREETING', 'GREETING'), ('CHECK_IN', 'CHECK_IN'), ('QUESTION', 'QUESTION'), ('COMMENT', 'COMMENT'), ('GOODBYE', 'GOODBYE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='thought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.thought'),
        ),
    ]
