# Generated by Django 3.1.10 on 2021-05-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20210519_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_check_in',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_greeting',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_question',
        ),
        migrations.AlterField(
            model_name='request',
            name='message_type',
            field=models.CharField(blank=True, choices=[('GIF', 'GIF'), ('IMAGE', 'IMAGE'), ('GREETING', 'GREETING'), ('CHECK_IN', 'CHECK_IN'), ('QUESTION', 'QUESTION'), ('COMMENT', 'COMMENT'), ('GOODBYE', 'GOODBYE')], max_length=20, null=True),
        ),
    ]
