# Generated by Django 3.1.11 on 2021-06-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20210524_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='message_type',
            field=models.CharField(blank=True, choices=[('GIF', 'GIF'), ('IMAGE', 'IMAGE'), ('GREETING', 'GREETING'), ('CHECK_IN', 'CHECK_IN'), ('QUESTION', 'QUESTION'), ('COMMENT', 'COMMENT')], max_length=20, null=True),
        ),
    ]
