# Generated by Django 3.1.11 on 2021-06-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20210604_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
