# Generated by Django 3.1.11 on 2021-06-26 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_request_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.groupmebot'),
        ),
    ]
