# Generated by Django 3.1.11 on 2021-06-26 03:22

from django.db import migrations


def create_objects(apps, schema_editor):
    bot_model = apps.get_model("bot", "GroupMeBot")
    thought_model = apps.get_model("bot", "Thought")

    bbot_id = bot_model.objects.filter(name='bbot').first()

    if bbot_id:
        for thought in thought_model.objects.all():
            thought.bot_id = bbot_id
            thought.save() 


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_thought_bot'),
    ]

    operations = [
        migrations.RunPython(create_objects, reverse_code=migrations.RunPython.noop),
    ]
