# Generated by Django 3.1.11 on 2021-06-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_gamebot_gamecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecomment',
            name='time',
            field=models.CharField(blank=True, choices=[('START', 'Start'), ('DRAW', 'Draw'), ('POSTCUT', 'Post Cut'), ('PLAY', 'Play'), ('HAND', 'Hand'), ('CRIB', 'Crib'), ('GAME_OVER', 'Game Over')], default='DRAW', max_length=100, null=True),
        ),
    ]
